[workspace]
resolver = "3"
members = ["chaud"]

[workspace.package]
license = "MIT OR Apache-2.0"
repository = "https://github.com/TimNN/chaud"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "forbid"

[workspace.lints.clippy]
multiple_unsafe_ops_per_block = "warn"
self_named_module_files = "warn"
undocumented_unsafe_blocks = "warn"
unused_trait_names = "warn"

pedantic = { level = "warn", priority = -1 }
