name: ci
on:
  pull_request:
  push:
    branches:
      - master
      - dev
  schedule:
    # Daily, at a semi-randomly chosen time.
    - cron: "37 3 * * *"

permissions:
  contents: read

jobs:
  test-full:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        rust: ["stable", "beta", "nightly"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy, rustfmt

      - name: Check Format
        if: ${{ matrix.rust == 'stable' }}
        run: cargo fmt --all --check

      - name: Clippy
        run: cargo clippy --workspace --all-features -- -D warnings

      - name: Documentation
        run:
          cargo doc --workspace --all-features --no-deps
          --document-private-items
        env:
          RUSTDOCFLAGS: -D warnings

      - name: Install
        run: cargo install --path chaud-cli

      - name: Tests
        run: cargo test --workspace
